dependencies {

    // Published dependencies
    api("codechicken:codechickenlib:3.2.3.358")
    api("com.cleanroommc:modularui:2.4.3") { transitive = false }

    api rfg.deobf("curse.maven:ctm-267602:2915363")

    // Hard Dependencies
    implementation(rfg.deobf("curse.maven:gregtech-ce-unofficial-557242:5519022"))
    implementation(rfg.deobf("curse.maven:gregicality-multiblocks-564858:5619513"))
    implementation rfg.deobf("curse.maven:ae2-extended-life-570458:6302098")
}